# Generated by Django 4.0.3 on 2022-03-17 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inmates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hostel_ID', models.CharField(max_length=30, null=True)),
                ('Name', models.CharField(max_length=100, null=True)),
                ('Room_Num', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
