# Generated by Django 4.0.3 on 2022-04-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Preference', models.CharField(max_length=20, null=True)),
                ('Present_Amount', models.IntegerField(null=True)),
                ('MC', models.IntegerField(null=True)),
            ],
        ),
    ]
