# Generated by Django 4.0.3 on 2022-04-06 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Details',
        ),
        migrations.AddField(
            model_name='inmates',
            name='MC',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='inmates',
            name='Preference',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='inmates',
            name='Present_Amount',
            field=models.IntegerField(null=True),
        ),
    ]
