# Generated by Django 4.0.3 on 2022-04-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_details_inmates_mc_inmates_preference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmates',
            name='Marked',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
