# Generated by Django 4.0.3 on 2022-04-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_inmates_marked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inmates',
            old_name='Present_Amount',
            new_name='Bill_Amount',
        ),
        migrations.AlterField(
            model_name='inmates',
            name='Marked',
            field=models.IntegerField(null=True),
        ),
    ]
