# Generated by Django 4.0.3 on 2022-04-16 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_present_amount_inmates_bill_amount_and_more'),
    ]

    operations = [
    ]
